include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    one_member_abstracts: ignore
    todo: ignore
    dead_code: error
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
linter:
  rules:
    directives_ordering: true
    prefer_relative_imports: true
    library_private_types_in_public_api: false
    require_trailing_commas: true
    prefer_single_quotes: true
    unnecessary_lambdas: true
    use_if_null_to_convert_nulls_to_bools: true
    prefer_final_locals: true
