targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/src/presentation/i18n
          output_file_name: translations.g.dart
          lazy: true
          locale_handling: false
          translation_class_visibility: public
          flutter_integration: true
          namespaces: true
          string_interpolation: braces
          pluralization:
            default_parameter: count