coverage:
  precision: 2
  range: "50...90"
  status:
    project:
      default:
        threshold: 5%
        paths: 
          - "lib/"

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/main.dart"
  - "**/infrastructure/*"
  - "**/navigation/*"
  - "**/presentation/*"
  - "**/interfaces/*"