coverage:
  precision: 2
  round: down
  range: "50...90"

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "lib/main.dart"
  - "lib/src/infrastructure/*"
  - "lib/src/navigation/*"
  - "lib/src/presentation/*"
  - "lib/src/data/interfaces/*"