codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...90"

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/main.dart"
  - "**/infrastructure/*"
  - "**/navigation/*"
  - "**/presentation/*"
  - "**/interfaces/*"

status:
  project:
    default:
      threshold: 1% # Minimum coverage required to show status
      paths: 
        - "lib/"